import { DEFAULT_ACCESSIBILITY } from "../ui/accessibility.js";
import { UNRESOLVED_FINALE, type LandDefinition } from "./dna.js";

function land(
  definition: Omit<LandDefinition, "displayName" | "accessibilityDefaults" | "finale"> & {
    finale?: LandDefinition["finale"];
  },
): LandDefinition {
  return {
    ...definition,
    displayName: definition.name,
    accessibilityDefaults: { ...DEFAULT_ACCESSIBILITY },
    finale: definition.finale ?? UNRESOLVED_FINALE,
  };
}

export const LAND_CATALOG: readonly LandDefinition[] = [
  land({
    id: "lumina",
    slug: "lumina",
    name: "Lumina",
    philosophicalQuestion: "Who are you?",
    coreTheme: "identity and recognition",
    designPrinciple: "Look carefully.",
    mechanicalLanguage: [
      "reflection",
      "illumination",
      "radiance",
      "recognition",
      "locks",
      "revealing",
      "mirrored spaces",
      "connected light",
    ],
    mechanicalVerbs: ["illuminate", "reflect", "reveal", "lock", "unlock", "connect"],
    boardLanguage: "identity-silhouette",
    movementLanguage: "connected-light-paths",
    matchLanguage: "recognition-clusters",
    obstacleLanguage: "locks-and-hidden-radiance",
    objectiveLanguage: "reveal-and-recognize",
    mechanicRegistry: ["land.lumina"],
    mechanicHandlerId: "land.lumina",
    difficultyBias: { planningDepth: 4, spatialAwareness: 5, mechanicComplexity: 3 },
    visualLanguage: "radiance and mirrored silhouettes",
    audioLanguage: "reveal chimes",
    accessibilityConsiderations: {
      reducedMotion: "Illumination pulses must have a static pattern equivalent.",
      nonColorOnly: "Recognition never uses hue alone; every state has a pattern and label.",
      textState: "Locks and reveals announce named cell state.",
      audioCues: "Optional chime on reveal.",
      hapticCues: "Optional tap on unlock.",
      timingAccommodations: "No reflex window is required to observe.",
      stateChangeIndication: "Revealed cells gain a non-color mark and spoken name.",
    },
    iconFamilyId: "lumina.ordinary",
    progression: {
      order: 1,
      packPrefix: "lumina",
      mechanicIntroductionRefs: [],
      difficultyTendencies: { planningDepth: 4, spatialAwareness: 5 },
      finaleDesignation: "level-80-signature",
      gateTransitionRefs: [],
    },
    narrativeIdentity: "self-recognition",
  }),
  land({
    id: "glimmer",
    slug: "glimmer",
    name: "Glimmer",
    philosophicalQuestion: "How do you express yourself?",
    coreTheme: "expression and performance",
    designPrinciple: "Express yourself.",
    mechanicalLanguage: [
      "rhythm",
      "performance",
      "stage movement",
      "spotlight",
      "timing",
      "sequencing",
      "performance chains",
      "movement through space",
    ],
    mechanicalVerbs: ["spotlight", "sequence", "rotate", "shift", "occupy", "connect"],
    boardLanguage: "performance-stage",
    movementLanguage: "stage-traversal",
    matchLanguage: "performance-chains",
    obstacleLanguage: "spotlight-and-curtains",
    objectiveLanguage: "sequence-and-express",
    mechanicRegistry: ["land.glimmer"],
    mechanicHandlerId: "land.glimmer",
    difficultyBias: { planningDepth: 5, timingDemand: 3, multitasking: 4 },
    visualLanguage: "stage light and motion trails",
    audioLanguage: "beat accents",
    accessibilityConsiderations: {
      reducedMotion: "Spotlight travel has a discrete step mode.",
      nonColorOnly: "Rhythm steps are numbered and labeled, never color-only.",
      textState: "Sequence progress is announced as step N of M.",
      audioCues: "Optional beat cue; never required for legality.",
      hapticCues: "Optional pulse on sequence step.",
      timingAccommodations: "Timing demand is optional. Puzzle thinking stays central; no reflex-only clear.",
      stateChangeIndication: "Active spotlight cell has a pattern badge plus label.",
    },
    iconFamilyId: "glimmer.ordinary",
    progression: {
      order: 2,
      packPrefix: "glimmer",
      mechanicIntroductionRefs: [],
      difficultyTendencies: { planningDepth: 5, timingDemand: 3, multitasking: 4 },
      finaleDesignation: "level-80-signature",
      gateTransitionRefs: [],
    },
    narrativeIdentity: "expression",
  }),
  land({
    id: "bloomara",
    slug: "bloomara",
    name: "Bloomara",
    philosophicalQuestion: "What connects you?",
    coreTheme: "connection and pairing",
    designPrinciple: "Connection changes the board.",
    mechanicalLanguage: [
      "mirroring",
      "pairing",
      "synchronization",
      "dual states",
      "linked cells",
      "mirrored chambers",
      "paired paths",
    ],
    mechanicalVerbs: ["pair", "synchronize", "connect", "reflect", "separate"],
    boardLanguage: "paired-chambers",
    movementLanguage: "linked-paths",
    matchLanguage: "paired-correspondence",
    obstacleLanguage: "mirrors-and-bonds",
    objectiveLanguage: "synchronize-and-connect",
    mechanicRegistry: ["land.bloomara"],
    mechanicHandlerId: "land.bloomara",
    difficultyBias: { spatialAwareness: 6, topologyComplexity: 5, multitasking: 5 },
    visualLanguage: "paired chambers and twin marks",
    audioLanguage: "harmonic pairs",
    accessibilityConsiderations: {
      reducedMotion: "Mirror updates apply instantly when reduced motion is on.",
      nonColorOnly: "Paired cells share a pattern id and spoken pair name.",
      textState: "Each link announces both cell ids.",
      audioCues: "Optional pair-confirm tone.",
      hapticCues: "Optional dual-tap on sync.",
      timingAccommodations: "Synchronization is turn-based, not twitch.",
      stateChangeIndication: "Linked state is listed as cell A ↔ cell B.",
    },
    iconFamilyId: "bloomara.ordinary",
    progression: {
      order: 3,
      packPrefix: "bloomara",
      mechanicIntroductionRefs: [],
      difficultyTendencies: { spatialAwareness: 6, topologyComplexity: 5, multitasking: 5 },
      finaleDesignation: "level-80-signature",
      gateTransitionRefs: [],
    },
    narrativeIdentity: "connection",
  }),
  land({
    id: "transcendia",
    slug: "transcendia",
    name: "Transcendia",
    philosophicalQuestion: "What are you becoming?",
    coreTheme: "transformation and becoming",
    designPrinciple: "Change creates possibility.",
    mechanicalLanguage: [
      "transformation",
      "elevation",
      "metamorphosis",
      "progression",
      "portals",
      "ascending structures",
      "evolving states",
    ],
    mechanicalVerbs: ["transform", "ascend", "elevate", "evolve", "shift", "connect"],
    boardLanguage: "ascent-path",
    movementLanguage: "elevation-routes",
    matchLanguage: "evolving-groups",
    obstacleLanguage: "cocoons-and-portals",
    objectiveLanguage: "transform-and-ascend",
    mechanicRegistry: ["land.transcendia"],
    mechanicHandlerId: "land.transcendia",
    difficultyBias: { mechanicComplexity: 6, planningDepth: 5, cascadeDependency: 4 },
    visualLanguage: "ascent and metamorphosis marks",
    audioLanguage: "rising tones",
    accessibilityConsiderations: {
      reducedMotion: "Transformations snap to the next authored state.",
      nonColorOnly: "Evolution stages have names and stage numbers.",
      textState: "Each transform announces previous → next state.",
      audioCues: "Optional rise cue.",
      hapticCues: "Optional lift pulse.",
      timingAccommodations: "State evolution is move-driven.",
      stateChangeIndication: "Stage badges stay readable after the visual changes.",
    },
    iconFamilyId: "transcendia.ordinary",
    progression: {
      order: 4,
      packPrefix: "transcendia",
      mechanicIntroductionRefs: [],
      difficultyTendencies: { mechanicComplexity: 6, planningDepth: 5, cascadeDependency: 4 },
      finaleDesignation: "level-80-signature",
      gateTransitionRefs: [],
    },
    narrativeIdentity: "becoming",
  }),
  land({
    id: "quintara",
    slug: "quintara",
    name: "Quintara",
    philosophicalQuestion: "What do you believe?",
    coreTheme: "belief, uncertainty, and revelation",
    designPrinciple: "Not everything is what it appears to be.",
    mechanicalLanguage: [
      "deception",
      "uncertainty",
      "shifting paths",
      "hidden routes",
      "misdirection",
      "maze logic",
      "false choices",
      "revelation",
    ],
    mechanicalVerbs: ["conceal", "reveal", "shift", "misdirect", "redirect"],
    boardLanguage: "belief-labyrinth",
    movementLanguage: "shifting-authored-routes",
    matchLanguage: "revelation-clusters",
    obstacleLanguage: "false-doors-and-hidden-routes",
    objectiveLanguage: "learn-and-reveal",
    mechanicRegistry: ["land.quintara"],
    mechanicHandlerId: "land.quintara",
    difficultyBias: { planningDepth: 7, topologyComplexity: 6, rngSensitivity: 1 },
    visualLanguage: "labyrinth marks and veil patterns",
    audioLanguage: "uncertain then resolving chords",
    accessibilityConsiderations: {
      reducedMotion: "Path shifts are discrete graph updates.",
      nonColorOnly: "False vs true routes use pattern and label, never hue alone.",
      textState: "Hidden routes announce themselves when revealed.",
      audioCues: "Optional reveal cue.",
      hapticCues: "Optional confirm on a learned true route.",
      timingAccommodations: "Misdirection is logical and turn-based. No arbitrary RNG confusion.",
      stateChangeIndication: "Learned routes persist as named, inspectable edges.",
    },
    iconFamilyId: "quintara.ordinary",
    progression: {
      order: 5,
      packPrefix: "quintara",
      mechanicIntroductionRefs: [],
      difficultyTendencies: { planningDepth: 7, topologyComplexity: 6, rngSensitivity: 1 },
      finaleDesignation: "level-80-signature",
      gateTransitionRefs: [],
    },
    narrativeIdentity: "belief",
  }),
  land({
    id: "iridescia",
    slug: "iridescia",
    name: "Iridescia",
    philosophicalQuestion: "Can you flow?",
    coreTheme: "flow and currents",
    designPrinciple: "Move with the system.",
    mechanicalLanguage: [
      "flow",
      "currents",
      "floating structures",
      "organic movement",
      "drift",
      "connected movement",
      "changing pathways",
    ],
    mechanicalVerbs: ["flow", "drift", "redirect", "connect", "shift"],
    boardLanguage: "flow-current",
    movementLanguage: "authored-currents",
    matchLanguage: "drift-clusters",
    obstacleLanguage: "floating-structures",
    objectiveLanguage: "flow-and-redirect",
    mechanicRegistry: ["land.iridescia"],
    mechanicHandlerId: "land.iridescia",
    difficultyBias: { spatialAwareness: 6, cascadeDependency: 5, topologyComplexity: 5 },
    visualLanguage: "currents and iridescent trails",
    audioLanguage: "water-like washes",
    accessibilityConsiderations: {
      reducedMotion: "Drift is a single settle step, not a continuous animation.",
      nonColorOnly: "Current direction uses edge labels, not color gradients.",
      textState: "Flow edges announce from → to.",
      audioCues: "Optional current cue.",
      hapticCues: "Optional settle pulse.",
      timingAccommodations: "Flow resolves in the cascade pipeline, not a reflex window.",
      stateChangeIndication: "Changed pathways list the edge ids that opened or closed.",
    },
    iconFamilyId: "iridescia.ordinary",
    progression: {
      order: 6,
      packPrefix: "iridescia",
      mechanicIntroductionRefs: [],
      difficultyTendencies: { spatialAwareness: 6, cascadeDependency: 5, topologyComplexity: 5 },
      finaleDesignation: "level-80-signature",
      gateTransitionRefs: [],
    },
    narrativeIdentity: "flow",
  }),
  land({
    id: "aurelia",
    slug: "aurelia",
    name: "Aurelia",
    philosophicalQuestion: "What will you protect?",
    coreTheme: "territory and protection",
    designPrinciple: "Position is power.",
    mechanicalLanguage: [
      "territory",
      "protection",
      "positioning",
      "strategic control",
      "boundaries",
      "fortified spaces",
      "central courts",
      "defensive structures",
    ],
    mechanicalVerbs: ["protect", "occupy", "lock", "unlock", "fortify", "connect", "separate"],
    boardLanguage: "ward-and-throne",
    movementLanguage: "court-positioning",
    matchLanguage: "territory-control",
    obstacleLanguage: "fortifications-and-wards",
    objectiveLanguage: "protect-and-occupy",
    mechanicRegistry: ["land.aurelia"],
    mechanicHandlerId: "land.aurelia",
    difficultyBias: { planningDepth: 6, spatialAwareness: 6, recoveryDifficulty: 4 },
    visualLanguage: "courts, wards, and seals",
    audioLanguage: "heraldic hits",
    accessibilityConsiderations: {
      reducedMotion: "Territory fills apply as a static overlay.",
      nonColorOnly: "Owned cells use crest patterns and names, never team color alone.",
      textState: "Protected cells announce owner and durability.",
      audioCues: "Optional ward cue.",
      hapticCues: "Optional fortify tap.",
      timingAccommodations: "Control is positional and turn-based.",
      stateChangeIndication: "Boundary changes list cell ids that entered or left a ward.",
    },
    iconFamilyId: "aurelia.ordinary",
    progression: {
      order: 7,
      packPrefix: "aurelia",
      mechanicIntroductionRefs: [],
      difficultyTendencies: { planningDepth: 6, spatialAwareness: 6, recoveryDifficulty: 4 },
      finaleDesignation: "level-80-signature",
      gateTransitionRefs: [],
    },
    narrativeIdentity: "protection",
  }),
  land({
    id: "infinity-isles",
    slug: "infinity-isles",
    name: "Infinity Isles",
    philosophicalQuestion: "What is possible?",
    coreTheme: "possibility and spatial paradox",
    designPrinciple: "Possibility has no edge.",
    mechanicalLanguage: [
      "orbit",
      "gravity",
      "celestial movement",
      "spatial paradox",
      "portals",
      "orbital rings",
      "floating islands",
      "wormholes",
    ],
    mechanicalVerbs: ["orbit", "redirect", "connect", "transform", "flow", "wormhole"],
    boardLanguage: "possibility-archipelago",
    movementLanguage: "orbital-and-portal-graph",
    matchLanguage: "celestial-clusters",
    obstacleLanguage: "islands-and-wormholes",
    objectiveLanguage: "orbit-and-connect",
    mechanicRegistry: ["land.infinity-isles"],
    mechanicHandlerId: "land.infinity-isles",
    difficultyBias: { spatialAwareness: 8, topologyComplexity: 8, mechanicComplexity: 6 },
    visualLanguage: "islands, rings, and star maps",
    audioLanguage: "orbital harmonics",
    accessibilityConsiderations: {
      reducedMotion: "Orbits step along authored cycles, not continuous spin.",
      nonColorOnly: "Islands and wormholes have names and pattern ids.",
      textState: "Paradox routes announce both endpoints and direction labels.",
      audioCues: "Optional portal cue.",
      hapticCues: "Optional orbit step pulse.",
      timingAccommodations: "Aggressive spatial layout stays turn-based and internally consistent.",
      stateChangeIndication: "Orbit and wormhole changes list cell and edge ids.",
    },
    iconFamilyId: "infinity-isles.ordinary",
    progression: {
      order: 8,
      packPrefix: "infinity-isles",
      mechanicIntroductionRefs: [],
      difficultyTendencies: { spatialAwareness: 8, topologyComplexity: 8, mechanicComplexity: 6 },
      finaleDesignation: "level-80-signature",
      gateTransitionRefs: [],
    },
    narrativeIdentity: "possibility",
  }),
];
